use_frameworks!

platform :ios, '8.0'

target 'RestKitUI_Example' do
  pod 'RestKitUI', :path => '../'

  pod 'Alamofire', '~> 4.0'

  target 'RestKitUI_Tests' do
    inherit! :search_paths
   
  end
end
